name: Build and deploy #.NET Core application to Web App BPCalculator20231220025453

on:
  workflow_dispatch:
  #push:
    #branches:
    #- main

env:
  AZURE_WEBAPP_NAME: BPCalculator2023-VA
  AZURE_WEBAPP_PACKAGE_PATH: Publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: BPCalculator

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: development

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: dotnet restore ${{ env.WORKING_DIRECTORY }}

    - name: Build
      run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore
      
    - name: Run Unit Tests
      run: dotnet test ./BPCalculatorUnitTests/BPCalculatorUnitTests.csproj --logger "trx;LogFileName=./TestResults/BPCalculatorUnitTests.trx" --collect "Code coverage"
    
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      with:
        artifact : ''            # Name of the check run which will be created
        name : MS Tests
        path: '**.trx'    # Path to test results
        reporter: 'dotnet-trx'

    - name: Publish
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
           echo ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
           echo "##vso[artifact.publish containerfolder=Publish;artifactname=webapp]Publish/**"
       
    - name: Run UAT Tests
      run: dotnet test ./UATTests/UATTests.csproj --logger "trx;LogFileName=./TestResults/UATTests.trx" --collect "Code coverage" 

      

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  test:
    runs-on: windows-latest
    needs: deploy
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    - name: Run Selenium Tests
      run: dotnet test .\SeleniumTests\SeleniumTests.csproj --logger "trx;LogFileName=.\TestResults\SeleniumTests.trx" --collect "Code coverage" 

    

    - name: Publish Selenium Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        files: .\TestResults\SeleniumTests.trx
