name: Build & Publish 🚀

on:
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: BPCalculator-VA1
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Install Dependencies
        run: dotnet restore ./BPCalculator.sln
        
      - name: Build
        run: dotnet build ./BPCalculator.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test ./BPCalculatorUnitTests/BPCalculatorUnitTests.csproj --logger "trx;LogFileName=./TestResults/BPCalculatorUnitTests.trx" --collect "Code coverage"
    
      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1
        with:
          artifact : ''            # Name of the check run which will be created
          name : MS Tests
          path: '**.trx'    # Path to test results
          reporter: 'dotnet-trx'

      - name: Azure Login
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         
      - name: Publish
        run: dotnet publish ./BPCalculator.sln --configuration Release --no-build --property PublishDir=${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  #--output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with: 
          name: BPcalculator
          path: '**/publish/'
          
  deploy : 
    runs-on: ubuntu-latest
    needs: build
    environment :
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: BPcalculator
          path: BPCalculator/publish
          
      - name: Azure Login
        uses: azure/login@v1
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
         
      - name: Deploy to Azure Web App
        id: deploy-to-webapp    
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE1 }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
